name: Deploying Demo

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out"
        uses: actions/checkout@v3
      - name: "Setting up Flutter SDK"
        uses: subosito/flutter-action@v2
      - name: "Setting up Pages"
        uses: actions/configure-pages@v3
      - name: "Building for web"
        working-directory: ./example
        run: flutter build web --release --verbose --base-href "/color_tweened/"
      - name: "Uploading artifact"
        uses: actions/upload-pages-artifact@v2
        with:
          path: './example/build/web/'
      - name: "Deploying to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v2